spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/e_learning
    username: root
    password: root
  data:
    rest:
      base-path: /

server:
  port: 3001

logging:
  level:
    com.example.elearning: DEBUG

springdoc:
  swagger-ui:
    path: "/swagger-ui"

---

spring:
  config:
    activate:
      on-profile: "production"

server:
  port: 0

logging:
  level:
    com.example.elearning: WARN
